export const ScreenName = {
	Singin: "Singin",
	Tabs: "Tabs",
	Home: "TabsHome",
	Mine: "TabsMine",
	Categories: "TabsCategories",
	Settings: "Settings",
	Post: "Post",
	Posts: "Posts",
	PostNew: "PostNew",
	WebView: "WebView",
	Signin: "Signin",
	Authenticate: "Authenticate",
	Search: "Search",
	CategoriesSort: "CategoriesSort",
	User: "User",
} as const;
